import { Group, Article, User } from '../../../interface/interface';

// Dữ liệu mẫu cho các bài viết (Articles)
export const articles: Article[] = [
  {
    _id: 'article1',
    sharedPostId: null,
    idHandler: 'user1',
    handleDate: new Date(),
    reports: [],
    groupID: 'group1',
    content: 'Chào mừng mọi người đến với Group 1. Đây là bài viết đầu tiên!',
    hashTag: ['#welcome', '#firstPost'],
    listPhoto: ['/src/assets/images/avt.png'],
    scope: 'public',
    interact: {
      _id: 'interact1',
      emoticons: [],
      comment: [],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    _destroy:  new Date()
  },
  {
    _id: 'article2',
    sharedPostId: null,
    idHandler: 'user2',
    handleDate: new Date(),
    reports: [],
    groupID: 'group1',
    content: 'Mọi người đã chuẩn bị gì cho sự kiện sắp tới chưa?',
    hashTag: ['#event', '#group1'],
    listPhoto: ['/src/assets/images/avt.png'],
    scope: 'public',
    interact: {
      _id: 'interact2',
      emoticons: [],
      comment: [],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    _destroy:  new Date()
  },
  {
    _id: 'article3',
    sharedPostId: null,
    idHandler: 'user3',
    handleDate: new Date(),
    reports: [],
    groupID: 'group2',
    content: 'Chia sẻ cảm nghĩ của mọi người về Group 2.',
    hashTag: ['#thoughts', '#group2'],
    listPhoto: ['/src/assets/images/avt.png'],
    scope: 'public',
    interact: {
      _id: 'interact3',
      emoticons: [],
      comment: [],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    _destroy:  new Date()
  },
  {
    _id: 'article4',
    sharedPostId: null,
    idHandler: 'user4',
    handleDate: new Date(),
    reports: [],
    groupID: 'group3',
    content: 'Hôm nay là ngày vui của mình! Cảm ơn tất cả các bạn.',
    hashTag: ['#happyDay', '#group3'],
    listPhoto: ['/src/assets/images/avt.png'],
    scope: 'public',
    interact: {
      _id: 'interact4',
      emoticons: [],
      comment: [],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    _destroy:  new Date()
  },
  {
    _id: 'article5',
    sharedPostId: null,
    idHandler: 'user5',
    handleDate: new Date(),
    reports: [],
    groupID: 'group1',
    content: 'Thảo luận về dự án mới của Group 1',
    hashTag: ['#project', '#group1'],
    listPhoto: ['/src/assets/images/avt.png'],
    scope: 'public',
    interact: {
      _id: 'interact5',
      emoticons: [],
      comment: [],
    },
    createdAt: new Date(),
    updatedAt: new Date(),
    _destroy:  new Date()
  },
];

// Dữ liệu mẫu cho người dùng (Users)
export const users: User[] = [
  {
    _id: 'user1',
    account: {
      warningLevel: 0,
      email: 'user1@example.com',
      password: 'password1',
    },
    firstName: 'John',
    lastName: 'Doe',
    displayName: 'John Doe',
    userName: 'johndoe',
    details: {
      phoneNumber: '1234567890',
      address: '123 Main St',
      gender: true,
      birthDate: new Date('1990-01-01'),
    },
    friends: [],
    status: 'active',
    avt: ['/src/assets/images/avt.png'],
    collections: [],
    groups: ['group1', 'group2'],
    backGround: ['/src/assets/images/avt.png'],
    aboutMe: 'Chào mừng đến với hồ sơ của tôi!',
    createDate: new Date().toString(),
    hobbies: ['Reading', 'Swimming'],
    listArticle: ['article1', 'article5'],
    createdAt: new Date(),
    updatedAt: new Date(),
    _destroy:  new Date()
  },
  {
    _id: 'user2',
    account: {
      warningLevel: 1,
      email: 'user2@example.com',
      password: 'password2',
    },
    firstName: 'Jane',
    lastName: 'Doe',
    displayName: 'Jane Doe',
    userName: 'janedoe',
    details: {
      phoneNumber: '0987654321',
      address: '456 Elm St',
      gender: false,
      birthDate: new Date('1992-05-15'),
    },
    friends: [],
    status: 'active',
    avt: ['/images/user2.jpg'],
    collections: [],
    groups: ['group1'],
    backGround: ['/images/bg2.jpg'],
    aboutMe: 'Tôi yêu thích công nghệ và âm nhạc.',
    createDate: new Date().toString(),
    hobbies: ['Music', 'Technology'],
    listArticle: ['article2'],
    createdAt: new Date(),
    updatedAt: new Date(),
    _destroy:  new Date()
  },
  {
    _id: 'user3',
    account: {
      warningLevel: 0,
      email: 'user3@example.com',
      password: 'password3',
    },
    firstName: 'Alice',
    lastName: 'Smith',
    displayName: 'Alice Smith',
    userName: 'alicesmith',
    details: {
      phoneNumber: '1122334455',
      address: '789 Oak St',
      gender: true,
      birthDate: new Date('1991-07-20'),
    },
    friends: [],
    status: 'active',
    avt: ['/images/user3.jpg'],
    collections: [],
    groups: ['group2', 'group3'],
    backGround: ['/images/bg3.jpg'],
    aboutMe: 'Alice yêu thể thao và du lịch.',
    createDate: new Date().toString(),
    hobbies: ['Sports', 'Travel'],
    listArticle: ['article3'],
    createdAt: new Date(),
    updatedAt: new Date(),
    _destroy:  new Date()
  },
  {
    _id: 'user4',
    account: {
      warningLevel: 0,
      email: 'user4@example.com',
      password: 'password4',
    },
    firstName: 'Bob',
    lastName: 'Johnson',
    displayName: 'Bob Johnson',
    userName: 'bobjohnson',
    details: {
      phoneNumber: '2233445566',
      address: '123 Pine St',
      gender: true,
      birthDate: new Date('1993-03-10'),
    },
    friends: [],
    status: 'active',
    avt: ['/images/user4.jpg'],
    collections: [],
    groups: ['group3'],
    backGround: ['/images/bg4.jpg'],
    aboutMe: 'Tôi yêu thiết kế và sáng tạo.',
    createDate: new Date().toString(),
    hobbies: ['Design', 'Art'],
    listArticle: ['article4'],
    createdAt: new Date(),
    updatedAt: new Date(),
    _destroy:  new Date()
  },
];

// Dữ liệu mẫu cho các nhóm (Groups)
export const groups: Group[] = [
  {
    _id: 'group1',
    warningLevel: 0,
    groupName: 'Group 1',
    type: 'public',
    idAdmin: 'user1',
    introduction: 'Đây là Group 1, nơi mọi người chia sẻ các ý tưởng thú vị.',
    avt: '/src/assets/images/avt.png',
    backGround: '/src/assets/images/avt.png',
    members: {
      count: 50,
      listUsers: [
        { idUser: 'user1', joinDate: new Date().toString() },
        { idUser: 'user2', joinDate: new Date().toString() },
        { idUser: 'user5', joinDate: new Date().toString() },
      ],
    },
    article: {
      count: 3,
      listArticle: [
        { idArticle: 'article1', state: 'approved' },
        { idArticle: 'article2', state: 'approved' },
        { idArticle: 'article5', state: 'approved' },
      ],
    },
    rule: ['No spamming', 'Respect others'],
    Administrators: [{ idUser: 'user1', joinDate: new Date().toString() }],
    hobbies: ['Music', 'Reading'],
    createdAt: new Date(),
    updatedAt: new Date(),
    _destroy:  new Date()
  },
  {
    _id: 'group2',
    warningLevel: 0,
    groupName: 'Group 2',
    type: 'private',
    idAdmin: 'user3',
    introduction: 'Chào mừng đến với Group 2, nhóm chuyên về thể thao và du lịch.',
    avt: '/src/assets/images/avt.png',
    backGround: '/src/assets/images/avt.png',
    members: {
      count: 30,
      listUsers: [
        { idUser: 'user1', joinDate: new Date().toString() },
        { idUser: 'user3', joinDate: new Date().toString() },
      ],
    },
    article: {
      count: 1,
      listArticle: [
        { idArticle: 'article3', state: 'approved' },
      ],
    },
    rule: ['Be polite', 'No offensive content'],
    Administrators: [{ idUser: 'user3', joinDate: new Date().toString() }],
    hobbies: ['Sports', 'Travel'],
    createdAt: new Date(),
    updatedAt: new Date(),
    _destroy:  new Date()
  },
  {
    _id: 'group3',
    warningLevel: 0,
    groupName: 'Group 3',
    type: 'public',
    idAdmin: 'user4',
    introduction: 'Đây là Group 3, chuyên về nghệ thuật và thiết kế.',
    avt: '/src/assets/images/avt.png',
    backGround: '/src/assets/images/avt.png',
    members: {
      count: 20,
      listUsers: [
        { idUser: 'user3', joinDate: new Date().toString() },
        { idUser: 'user4', joinDate: new Date().toString() },
      ],
    },
    article: {
      count: 1,
      listArticle: [
        { idArticle: 'article4', state: 'approved' },
      ],
    },
    rule: ['No plagiarism', 'Respect creativity'],
    Administrators: [{ idUser: 'user4', joinDate: new Date().toString() }],
    hobbies: ['Design', 'Art'],
    createdAt: new Date(),
    updatedAt: new Date(),
    _destroy:  new Date()
  },
];
